# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-03 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('C_ID', models.AutoField(primary_key=True, serialize=False)),
                ('C_Name', models.CharField(max_length=30, verbose_name='城市名')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('M_ID', models.AutoField(primary_key=True, serialize=False)),
                ('M_PostMessages', models.TextField(verbose_name='消息内容')),
                ('M_status', models.BooleanField(verbose_name='接收状态')),
                ('M_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
        ),
        migrations.CreateModel(
            name='MessagesType',
            fields=[
                ('MT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MT_Name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('P_ID', models.AutoField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=30, verbose_name='省份名')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('mobile_number', models.CharField(max_length=128, verbose_name='手机号码')),
                ('login_time', models.DateTimeField(auto_now=True, verbose_name='登录时间')),
                ('logout_time', models.DateTimeField(auto_now=True, verbose_name='退出时间')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('ip_address', models.CharField(max_length=15, verbose_name='IP地址')),
                ('is_active', models.IntegerField(default='1', verbose_name='是否有效')),
                ('friends', models.ManyToManyField(blank=True, related_name='_user_friends_+', to='verify.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('UG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('UG_Name', models.CharField(max_length=30, verbose_name='群名称')),
                ('UG_CreatTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('UG_ICon', models.CharField(max_length=30, verbose_name='群图标')),
                ('UG_Notice', models.CharField(max_length=200, verbose_name='群公告')),
                ('UG_Intro', models.CharField(max_length=200, verbose_name='群简介')),
                ('UG_AdminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='群主ID', to='verify.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_GroupsMSGContent',
            fields=[
                ('GM_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('GM_Content', models.TextField(verbose_name='消息内容')),
                ('GM_FromID', models.IntegerField(verbose_name='发送者ID')),
                ('GM_CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
        ),
        migrations.CreateModel(
            name='User_GroupsMSGToUser',
            fields=[
                ('GM_ID', models.AutoField(primary_key=True, serialize=False)),
                ('GM_UserID', models.IntegerField(verbose_name='接收者ID')),
                ('GM_State', models.BooleanField(verbose_name='接收状态')),
                ('GM_CreateTime', models.DateTimeField(auto_now=True, verbose_name='发送时间')),
                ('GM_GroupMessageID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='verify.User_GroupsMSGContent')),
            ],
        ),
        migrations.CreateModel(
            name='User_GroupsToUser',
            fields=[
                ('UG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('UG_CreateTime', models.DateTimeField(auto_now=True, verbose_name='发送时间')),
                ('UG_GroupID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='verify.User_Group')),
                ('UG_UserID', models.ManyToManyField(related_name='群用户ID', to='verify.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=128, verbose_name='昵称')),
                ('sex', models.IntegerField(verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('brithday', models.CharField(max_length=100, null=True, verbose_name='生日')),
                ('profile_head', models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='头像')),
                ('profile', models.CharField(max_length=255, null=True, verbose_name='个性签名')),
                ('city_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='省份ID', to='verify.City')),
                ('province_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='省份ID', to='verify.Province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='verify.User')),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='M_FromUserID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='发送者ID', to='verify.User'),
        ),
        migrations.AddField(
            model_name='messages',
            name='M_MessagesTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='消息类型ID', to='verify.MessagesType'),
        ),
        migrations.AddField(
            model_name='messages',
            name='M_ToUserID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='接收者ID', to='verify.User'),
        ),
        migrations.AddField(
            model_name='city',
            name='P_ProcvinceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='所属省份', to='verify.Province'),
        ),
    ]
