# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-03 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('C_ID', models.AutoField(primary_key=True, serialize=False)),
                ('C_Name', models.CharField(max_length=30, verbose_name='城市名')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('M_ID', models.AutoField(primary_key=True, serialize=False)),
                ('M_PostMessages', models.TextField(verbose_name='消息内容')),
                ('M_status', models.BooleanField(verbose_name='接收状态')),
                ('M_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
        ),
        migrations.CreateModel(
            name='MessagesType',
            fields=[
                ('MT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MT_Name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('P_ID', models.AutoField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=30, verbose_name='省份名')),
            ],
        ),
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('UG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('UG_Name', models.CharField(max_length=30, verbose_name='群名称')),
                ('UG_CreatTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('UG_ICon', models.CharField(max_length=30, verbose_name='群图标')),
                ('UG_Notice', models.CharField(max_length=200, verbose_name='群公告')),
                ('UG_Intro', models.CharField(max_length=200, verbose_name='群简介')),
            ],
        ),
        migrations.CreateModel(
            name='User_GroupsMSGContent',
            fields=[
                ('GM_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('GM_Content', models.TextField(verbose_name='消息内容')),
                ('GM_FromID', models.IntegerField(verbose_name='发送者ID')),
                ('GM_CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
        ),
        migrations.CreateModel(
            name='User_GroupsMSGToUser',
            fields=[
                ('GM_ID', models.AutoField(primary_key=True, serialize=False)),
                ('GM_UserID', models.IntegerField(verbose_name='接收者ID')),
                ('GM_State', models.BooleanField(verbose_name='接收状态')),
                ('GM_CreateTime', models.DateTimeField(auto_now=True, verbose_name='发送时间')),
                ('GM_GroupMessageID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='verify.User_GroupsMSGContent')),
            ],
        ),
        migrations.CreateModel(
            name='User_GroupsToUser',
            fields=[
                ('UG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('UG_CreateTime', models.DateTimeField(auto_now=True, verbose_name='发送时间')),
                ('UG_GroupID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='verify.User_Group')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to='verify.User'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='brithday',
            field=models.CharField(max_length=100, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_head',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user_groupstouser',
            name='UG_UserID',
            field=models.ManyToManyField(related_name='群用户ID', to='verify.User'),
        ),
        migrations.AddField(
            model_name='user_group',
            name='UG_AdminId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='群主ID', to='verify.User'),
        ),
        migrations.AddField(
            model_name='messages',
            name='M_FromUserID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='发送者ID', to='verify.User'),
        ),
        migrations.AddField(
            model_name='messages',
            name='M_MessagesTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='消息类型ID', to='verify.MessagesType'),
        ),
        migrations.AddField(
            model_name='messages',
            name='M_ToUserID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='接收者ID', to='verify.User'),
        ),
        migrations.AddField(
            model_name='city',
            name='P_ProcvinceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='所属省份', to='verify.Province'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='city_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='省份ID', to='verify.City'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='province_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='省份ID', to='verify.Province'),
        ),
    ]
