# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default='1', verbose_name='是否有效'),
        ),
    ]
